[pytest]
testpaths = tests
norecursedirs = turnero_refactorizado venv .venv
python_files = test_*.py
filterwarnings =
    ignore::DeprecationWarning
    ignore::starlette.exceptions.StarletteDeprecationWarning
